# Changes here will be overwritten by Copier
_commit: 2f1e40f
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: false
email: nick@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
has_cli: false
initial_commit: true
open_source_license: MIT
package_name: aiooui
project_name: aiooui
project_short_description: Async OUI lookups
project_slug: aiooui
run_poetry_install: true
setup_github: true
setup_pre_commit: true

